name: test

on:
  workflow_dispatch: ~
  # schedule:
  #   - cron: "0 * * * *"  # Runs every hour at the beginning of the hour (0 minutes)

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - lines: 30
          - lines: 50
    steps:
      - name: Do it
        run: docker run --rm mingrammer/flog -n ${{ matrix.lines }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Wait for random time
        run: docker run --rm mingrammer/flog -n 10
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: docker run --rm mingrammer/flog -n 10
