name: test

on:
  workflow_dispatch: ~
  # schedule:
  #   - cron: "0 * * * *"  # Runs every hour at the beginning of the hour (0 minutes)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for random time
        run: docker run -it --rm mingrammer/flog -n 50
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: docker run -it --rm mingrammer/flog -n 100
